apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-blog-project-multi
  namespace: my-blog-project
  labels:
    app: my-blog-project-multi
    version: "1.0"
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: my-blog-project-multi
  template:
    metadata:
      labels:
        app: my-blog-project-multi
        version: "1.0"
    spec:
      imagePullSecrets:
      - name: ecr-secret
      containers:
      # 容器 1: FastAPI 應用
      - name: fastapi-app
        image: 728951503024.dkr.ecr.ap-east-2.amazonaws.com/my-blog-project:latest
        ports:
        - name: fastapi
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: fastapi
          initialDelaySeconds: 60
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: fastapi
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: PORT
          value: "8080"
        - name: ENV
          value: "production"
        - name: APP_NAME
          value: "fastapi-app"
          
      # 容器 2: Jekyll 網站
      - name: jekyll-site
        image: 728951503024.dkr.ecr.ap-east-2.amazonaws.com/jackycsie-github-io:latest
        ports:
        - name: jekyll
          containerPort: 4000
          protocol: TCP
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"
        livenessProbe:
          httpGet:
            path: /
            port: jekyll
          initialDelaySeconds: 90
          periodSeconds: 20
          timeoutSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: jekyll
          initialDelaySeconds: 45
          periodSeconds: 15
          timeoutSeconds: 10
          failureThreshold: 3
        env:
        - name: JEKYLL_ENV
          value: "production"
        - name: APP_NAME
          value: "jekyll-site"
