---
# FastAPI 應用服務
apiVersion: v1
kind: Service
metadata:
  name: fastapi-app
  namespace: my-blog-project
  labels:
    app: my-blog-project-multi
    service: fastapi
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: fastapi
    nodePort: 30080
    protocol: TCP
  selector:
    app: my-blog-project-multi
  sessionAffinity: None
---
# Jekyll 網站服務
apiVersion: v1
kind: Service
metadata:
  name: jekyll-site
  namespace: my-blog-project
  labels:
    app: my-blog-project-multi
    service: jekyll
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: jekyll
    nodePort: 30081
    protocol: TCP
  selector:
    app: my-blog-project-multi
  sessionAffinity: None
