apiVersion: v1
kind: Service
metadata:
  name: my-blog-project
  namespace: my-blog-project
  labels:
    app: my-blog-project
    service: web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: my-blog-project
  sessionAffinity: None
