name: CI

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v
        
    - name: Test Docker build
      run: |
        docker build -t my-blog-project .
        
    - name: Test Docker Compose
      run: |
        docker compose up -d
        sleep 15
        curl -f http://localhost:8080/healthz || exit 1
        docker compose down
        
    - name: Test health endpoint
      run: |
        docker compose up -d
        sleep 15
        response=$(curl -s -w "%{http_code}" http://localhost:8080/healthz)
        http_code="${response: -3}"
        if [ "$http_code" != "200" ]; then
          echo "Health check failed with HTTP code: $http_code"
          exit 1
        fi
        echo "Health check passed with HTTP code: $http_code"
        docker compose down
